config/routes.rb
Stis::Application.routes.draw do

  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'
  devise_for :admins, :controllers => { :registrations => "admin/registrations", :sessions => "admin/sessions", :passwords => "admin/passwords" }
  
  get "welcome/index"
  root "welcome#index"

  
  get "news/new", :to => "news#new"
  get "news/index", :to => "news#index"
  post "news/create"
  get "news/edit/:id", :to => "news#edit", as: :news_edit
  post "news/update/:id", :to => "news#update", as: :news_update
  delete "news/destroy/:id", :to => "news#destroy", as: :news_destroy

  get "banners/new", :to => "banners#new"
  get "banners/index", :to => "banners#index"
  post "banners/createBanners"
  get "banners/editBanners/:id", :to => "banners#editBanners", as: :banners_editBanners
  post "banners/updateBanners/:id", :to => "banners#updateBanners", as: :banners_updateBanners
  delete "banners/destroy/:id", :to => "banners#destroy", as: :banners_destroy

  get "testimonials/new", :to => "testimonials#new"
  get "testimonials/index", :to => "testimonials#index"
  get "testimonials/editTestimonials/:id", :to => "testimonials#editTestimonials", as: :testimonials_editTestimonials
  post "testimonials/updateTestimonials/:id", :to => "testimonials#updateTestimonials", as: :testimonials_updateTestimonials
  post "testimonials/createTestimonials"
  delete "testimonials/destroy/:id", :to => "testimonials#destroy", as: :testimonials_destroy
  
  devise_scope :admin do
  end

end

app/models/banners.rb
class Banners < ActiveRecord::Base
	validates :title, presence: true, length: {minimum: 5, maximum: 25}
	validates :descriptions, presence: true, length: {minimum: 5}
end

app/controllers/banners_controller.rb
class BannersController < ApplicationController

	def new
		@banners = Banners.new
	end

	def createBanners
		@banners = Banners.new(params_banners)
		if @banners.save
			redirect_to banners_index_path
		else
			render "new"
		end

	end

	def editBanners
		@editBanners = Banners.find(params[:id])
	end

	def updateBanners
		@editBanners = Banners.find(params[:id])
		if @editBanners.update(params[:banners].permit(:title, :descriptions))
			redirect_to banners_index_path	
		else
			render "editBanners"
		end	
	end

	def destroy
		@banners = Banners.find(params[:id])
		@banners.delete

		redirect_to banners_index_path
	end

	def show
		@banners = Banners.find(params[:id])
	end

	def index
		@banners = Banners.all	
	end

	private
	def params_banners
		params.require(:banners).permit(:title, :descriptions)
	end
end

app/helpers/banners_helper.rb
module BannersHelper
end

app/views/banners/editBanners.html.haml
%h3.text-center.page-header
  = "Editing This Banner => #{@editBanners.title}" 
= form_for :banners, url:{action: "updateBanners"}, html:{:class => "form-horizontal"} do |f|
  -if @editBanners.errors.any?
    %div#error_explanations
      %h3
        -@editBanners.errors.count
        = "Probihited Error"
      %ul
        - @editBanners.errors.full_messages.each do |p|
          %li
            = p
  %div.form-group
    =f.label 'Banner Title', {:class => 'col-lg-2 control-label'}
    %div.col-lg-4
      = f.text_field :title, {:class => 'form-control', :value => @editBanners.title}
  %div.form-group
    =f.label 'Banner Title', {:class => 'col-lg-2 control-label'}
    %div.col-lg-4
      = f.text_field :descriptions, {:class => 'form-control', :value => @editBanners.descriptions}
  %div.form-group
    %div.col-lg-offset-2.col-lg-10
      = f.submit "Update", :class => "btn btn-primary"
      = link_to 'All News', banners_index_path, :class => "btn btn-primary"

app/views/banners/index.html.haml
%h1.text-center.page-header
	All Banners
%h3.text-center
	Create New Banner
	= link_to 'Add Banner', banners_new_path, :class => "btn btn-primary"
	|
	= link_to 'Add Testimonials', testimonials_new_path, :class => "btn btn-primary"
	|
	= link_to 'Add News', news_new_path, :class => "btn btn-primary"
	=# link_to 'Edit', edit_post_path(@post), :class => "btn btn-primary"
%table.table.table-hover.table-condensed.text-center
	%tr
		%th.text-center
			Banner Title
		%th.text-center
			
			Banner Descriptions
		%th.text-center
			Options
	- @banners.each do |f|
		%tr
			%td 
				= f.title
			%td 
				= f.descriptions 
			%td
				= link_to banners_editBanners_path(f.id) do
					= content_tag :button, :class => "btn btn-primary" do
						= content_tag :apan, class: "glyphicon glyphicon-pencil" do
							=""
				|
				= link_to banners_destroy_path(f.id), method: :delete, data: { :confirm => 'Are you sure?' } do
					= content_tag :button, :class => "btn btn-danger" do
						= content_tag :span, class: "glyphicon glyphicon-remove" do
							=""

app/views/banners/new.html.haml
%h1.text-center.page-header
	Add Banner
= form_for :banners, url:{action: "createBanners"}, html:{:class => "form-horizontal"} do |f|
	-if @banners.errors.any?
		%div#error_explanations
			%h3
				-@banners.errors.count
				= "Probihited Error"
			%ul
				- @banners.errors.full_messages.each do |p|
					%li
						= p
	%div.form-group
		= f.label 'Banner Title', {:class => 'col-lg-2 control-label'}
		%div.col-lg-4
			= f.text_field :title, {:class => "form-control"} 
	%div.form-group
		= f.label 'Banner Description', {:class => 'col-lg-2 control-label'}
		%div.col-lg-4
			= f.text_field :descriptions, {:class => "form-control"} 	
	%div.form-group
		%div.col-lg-offset-2.col-lg-10
			= f.submit "Save", :class => "btn btn-primary"
			= link_to 'Back', banners_index_path, :class => "btn btn-primary"