config/routes.rb
Stis::Application.routes.draw do

  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'
  devise_for :admins, :controllers => { :registrations => "admin/registrations", :sessions => "admin/sessions", :passwords => "admin/passwords" }
  
  get "welcome/index"
  root "welcome#index"

  
  get "news/new", :to => "news#new"
  get "news/index", :to => "news#index"
  post "news/create"
  get "news/edit/:id", :to => "news#edit", as: :news_edit
  post "news/update/:id", :to => "news#update", as: :news_update
  delete "news/destroy/:id", :to => "news#destroy", as: :news_destroy

  get "banners/new", :to => "banners#new"
  get "banners/index", :to => "banners#index"
  post "banners/createBanners"
  get "banners/editBanners/:id", :to => "banners#editBanners", as: :banners_editBanners
  post "banners/updateBanners/:id", :to => "banners#updateBanners", as: :banners_updateBanners
  delete "banners/destroy/:id", :to => "banners#destroy", as: :banners_destroy

  get "testimonials/new", :to => "testimonials#new"
  get "testimonials/index", :to => "testimonials#index"
  get "testimonials/editTestimonials/:id", :to => "testimonials#editTestimonials", as: :testimonials_editTestimonials
  post "testimonials/updateTestimonials/:id", :to => "testimonials#updateTestimonials", as: :testimonials_updateTestimonials
  post "testimonials/createTestimonials"
  delete "testimonials/destroy/:id", :to => "testimonials#destroy", as: :testimonials_destroy
  
  devise_scope :admin do
  end

end

app/models/news.rb
class News < ActiveRecord::Base
	validates :newsTitle, presence: true, length: {minimum: 5}
	validates :text, presence: true, length: {minimum: 5}
end

app/controllers/news_controller.rb
class NewsController < ApplicationController

	def new
		@news = News.new
	end

	def edit
		@editNews = News.find(params[:id])
	end

	def update
		@editNews = News.find(params[:id]) 
		if @editNews.update(params[:news].permit(:newsTitle,:text, :sortNo))
			redirect_to news_index_path
		else
	 		render 'edit'
		end
	end

	def destroy
		@news = News.find(params[:id])
  		@news.destroy
 
 		redirect_to news_index_path
	end

	def index
		@news = News.all
	end

	def create
		#render text: params[:post].inspect
		@news = News.new(news_params)
		if	@news.save
			redirect_to news_index_path
		else
			render 'new'
		end
	end

	def show
		@news = News.find(params[:id])
	end

	private

	def news_params
    	params.require(:news).permit(:newsTitle, :text, :sortNo)
  	end

end

app/helpers/news_helper.rb
module NewsHelper
end

app/views/news/edit.html.haml
%h3.text-center.page-header
  = "Editing This News => #{@editNews.text}" 
= form_for :news, url:{action: "update"}, html:{:class => "form-horizontal"} do |f|
  -if @editNews.errors.any?
    %div#error_explanations
      %h3
        -@editNews.errors.count
        = "Probihited Error"
      %ul
        - @editNews.errors.full_messages.each do |p|
          %li
            = p
  %div.form-group
    =f.label 'News Title', {:class => 'col-lg-2 control-label'}
    %div.col-lg-4
      = f.text_field :newsTitle, {:class => 'form-control', :value => @editNews.newsTitle}
  %div.form-group
    =f.label 'News Descriptions', {:class => 'col-lg-2 control-label'}
    %div.col-lg-4
      = f.text_field :text, {:class => 'form-control', :value => @editNews.text}
  %div.form-group
    %div.col-lg-offset-2.col-lg-10
      = f.submit "Update", :class => "btn btn-primary"
      = link_to 'All News', news_index_path, :class => "btn btn-primary"

app/views/news/index.html.haml
%h1.text-center.page-header
	All News
%h3.text-center
	Add New News
	= link_to 'Add News', news_new_path, :class => "btn btn-primary"
	|
	= link_to 'Add Testmonials', testimonials_new_path, :class => "btn btn-primary"
	|
	= link_to 'Add Banners', banners_new_path, :class => "btn btn-primary"
	=# link_to 'Edit', edit_post_path(@post), :class => "btn btn-primary"
%table.table.table-hover.table-condensed.text-center
	%tr
		%th.text-center
			News Title
		%th.text-center
			News Descriptions
		%th.text-center
			Time
		%th.text-center
			Options
	- @news.each do |f|
		%tr
			%td
				= f.newsTitle
			%td 
				= f.text
			%td 
				= f.created_at 
			%td
				= link_to news_edit_path(f.id) do
					= content_tag :button, :class => "btn btn-primary" do
						= content_tag :apan, class: "glyphicon glyphicon-pencil" do
							=""
				|
				= link_to news_destroy_path(f.id), method: :delete, data: { :confirm => 'Are you sure?' } do
					= content_tag :button, :class => "btn btn-danger" do
						= content_tag :span, class: "glyphicon glyphicon-remove" do
							=""

app/views/news/new.html.haml
%h1.text-center.page-header
	Add News
= form_for :news, url: news_create_path, html:{:class => "form-horizontal"} do |f|
	-if @news.errors.any?
		%div#error_explanations
			%h3
				-@news.errors.count
				= "Probihited Error"
			%ul
				- @news.errors.full_messages.each do |p|
					%li
						= p
	%div.form-group
		= f.label 'News Title', {:class => 'col-lg-2 control-label'}
		%div.col-lg-4
			= f.text_field :newsTitle, {:class => "form-control"} 
	%div.form-group
		= f.label 'News Descriptions', {:class => 'col-lg-2 control-label'}
		%div.col-lg-4
			= f.text_field :text, {:class => "form-control"} 
	%div.form-group
		%div.col-lg-offset-2.col-lg-10
			= f.submit "Save", :class => "btn btn-primary"
			= link_to 'Back', news_index_path, :class => "btn btn-primary"