config/routes.rb
Stis::Application.routes.draw do

  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'
  devise_for :admins, :controllers => { :registrations => "admin/registrations", :sessions => "admin/sessions", :passwords => "admin/passwords" }
  
  get "welcome/index"
  root "welcome#index"

  
  get "news/new", :to => "news#new"
  get "news/index", :to => "news#index"
  post "news/create"
  get "news/edit/:id", :to => "news#edit", as: :news_edit
  post "news/update/:id", :to => "news#update", as: :news_update
  delete "news/destroy/:id", :to => "news#destroy", as: :news_destroy

  get "banners/new", :to => "banners#new"
  get "banners/index", :to => "banners#index"
  post "banners/createBanners"
  get "banners/editBanners/:id", :to => "banners#editBanners", as: :banners_editBanners
  post "banners/updateBanners/:id", :to => "banners#updateBanners", as: :banners_updateBanners
  delete "banners/destroy/:id", :to => "banners#destroy", as: :banners_destroy

  get "testimonials/new", :to => "testimonials#new"
  get "testimonials/index", :to => "testimonials#index"
  get "testimonials/editTestimonials/:id", :to => "testimonials#editTestimonials", as: :testimonials_editTestimonials
  post "testimonials/updateTestimonials/:id", :to => "testimonials#updateTestimonials", as: :testimonials_updateTestimonials
  post "testimonials/createTestimonials"
  delete "testimonials/destroy/:id", :to => "testimonials#destroy", as: :testimonials_destroy
  
  devise_scope :admin do
  end

end

app/models/testimonials.rb
class Testimonials < ActiveRecord::Base
	validates :clintsName, presence: true, length: {minimum: 5, maximun: 25}
	validates :clintsDescriptions, presence: true, length: {minimum: 5}
end

app/controllers/testimonials_controller.rb
class TestimonialsController < ApplicationController

	def new
		@testimonials = Testimonials.new
	end

	def createTestimonials
		@testimonials = Testimonials.new(params_testimonials)
		if @testimonials.save
			redirect_to testimonials_index_path
		else
			render "new"
		end
	end

	def updateTestimonials
		@editTestimonials = Testimonials.find(params[:id])
		if @editTestimonials.update(params[:testimonials].permit(:clintsName, :clintsDescriptions))
			redirect_to testimonials_index_path
		else
			render "editTestimonials"
		end
	end

	def editTestimonials
		@editTestimonials = Testimonials.find(params[:id])
	end
	def index
		@testimonials = Testimonials.all
	end

	def destroy
		@testimonials = Testimonials.find(params[:id])
		@testimonials.delete
		redirect_to testimonials_index_path		
	end

	private

	def params_testimonials
		params.require(:testimonials).permit(:clintsName, :clintsDescriptions)
	end

end

app/helpers/testimonials_helper.rb
module TestimonialsHelper
end

app/views/testimonials/editTestimonials.html.haml
%h3.text-center.page-header
  = "Editing This Clint Info => #{@editTestimonials.clintsName}" 
= form_for :testimonials, url:{action: "updateTestimonials"}, html:{:class => "form-horizontal"} do |f|
  -if @editTestimonials.errors.any?
    %div#error_explanations
      %h3
        -@editTestimonials.errors.count
        = "Probihited Error"
      %ul
        - @editTestimonials.errors.full_messages.each do |p|
          %li
            = p
  %div.form-group
    =f.label 'Clint Name', {:class => 'col-lg-2 control-label'}
    %div.col-lg-4
      = f.text_field :title, {:class => 'form-control', :value => @editTestimonials.clintsName}
  %div.form-group
    =f.label 'clints Descriptions', {:class => 'col-lg-2 control-label'}
    %div.col-lg-4
      = f.text_field :clintsDescriptions, {:class => 'form-control', :value => @editTestimonials.clintsDescriptions}
  %div.form-group
    %div.col-lg-offset-2.col-lg-10
      = f.submit "Update", :class => "btn btn-primary"
      = link_to 'All News', testimonials_index_path, :class => "btn btn-primary"

app/views/testimonials/index.html.haml
%h1.text-center.page-header
	All Testmonials
%h3.text-center
	Create New Clints
	= link_to 'Add Testimonials', testimonials_new_path, :class => "btn btn-primary"
	|
	= link_to 'Add News', news_new_path, :class => "btn btn-primary"
	|
	= link_to 'Add Banners', banners_new_path, :class => "btn btn-primary"
	=# link_to 'Edit', edit_post_path(@post), :class => "btn btn-primary"
%table.table.table-hover.table-condensed.text-center
	%tr
		%th.text-center
			Clints Name
		%th.text-center
			Clints Descriptions
		%th.text-center
			Options
	- @testimonials.each do |f|
		%tr
			%td 
				= f.clintsName
			%td 
				= f.clintsDescriptions 
			%td
				= link_to testimonials_editTestimonials_path(f.id) do
					= content_tag :button, :class => "btn btn-primary" do
						= content_tag :apan, class: "glyphicon glyphicon-pencil" do
							=""
				|
				= link_to testimonials_destroy_path(f.id), method: :delete, data: { :confirm => 'Are you sure?' } do
					= content_tag :button, :class => "btn btn-danger" do
						= content_tag :span, class: "glyphicon glyphicon-remove" do
							=""

app/views/testimonials/new.html.haml
%h1.text-center.page-header
	Add clints Info
= form_for :testimonials, url:{action: "createTestimonials"}, html:{:class => "form-horizontal"} do |f|
	-if @testimonials.errors.any?
		%div#error_explanations
			%h3
				-@testimonials.errors.count
				= "Probihited Error"
			%ul
				- @testimonials.errors.full_messages.each do |p|
					%li
						= p
	%div.form-group
		= f.label 'Clint Name', {:class => 'col-lg-2 control-label'}
		%div.col-lg-4
			= f.text_field :clintsName, {:class => "form-control"} 
	%div.form-group
		= f.label 'Clints Description', {:class => 'col-lg-2 control-label'}
		%div.col-lg-4
			= f.text_field :clintsDescriptions, {:class => "form-control"} 	
	%div.form-group
		%div.col-lg-offset-2.col-lg-10
			= f.submit "Save", :class => "btn btn-primary"
			= link_to 'Back', testimonials_index_path, :class => "btn btn-primary"