config/routes.rb
Stis::Application.routes.draw do

  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'
  devise_for :admins, :controllers => { :registrations => "admin/registrations", :sessions => "admin/sessions", :passwords => "admin/passwords" }
  
  get "welcome/index"
  root "welcome#index"

  
  get "news/new", :to => "news#new"
  get "news/index", :to => "news#index"
  post "news/create"
  get "news/edit/:id", :to => "news#edit", as: :news_edit
  post "news/update/:id", :to => "news#update", as: :news_update
  delete "news/destroy/:id", :to => "news#destroy", as: :news_destroy

  get "banners/new", :to => "banners#new"
  get "banners/index", :to => "banners#index"
  post "banners/createBanners"
  get "banners/editBanners/:id", :to => "banners#editBanners", as: :banners_editBanners
  post "banners/updateBanners/:id", :to => "banners#updateBanners", as: :banners_updateBanners
  delete "banners/destroy/:id", :to => "banners#destroy", as: :banners_destroy

  get "testimonials/new", :to => "testimonials#new"
  get "testimonials/index", :to => "testimonials#index"
  get "testimonials/editTestimonials/:id", :to => "testimonials#editTestimonials", as: :testimonials_editTestimonials
  post "testimonials/updateTestimonials/:id", :to => "testimonials#updateTestimonials", as: :testimonials_updateTestimonials
  post "testimonials/createTestimonials"
  delete "testimonials/destroy/:id", :to => "testimonials#destroy", as: :testimonials_destroy
  
  devise_scope :admin do
  end

end

app/views/layouts/application.html.haml
<!DOCTYPE html>
%html
	%head
		%title SciTech
		= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true
		= javascript_include_tag "application", "data-turbolinks-track" => true
		= csrf_meta_tags
	%body
		/
			-if admin_signed_in?
				=# render "shared/header"
				=link_to "Edit Account", edit_admin_registration_path, :method => :get, :class => "btn btn-primary"
				%h3.text-center.page-header
					You have succesfully signed in
				=link_to "Sign Out", destroy_admin_session_path, :method => :delete, :class => "btn btn-primary"
			-else
				%h1.text-center.page-header
					Welcome to Scitech It Services
				%div.text-center
					=link_to "Sign In", new_admin_session_path, :method => :get, :class => "btn btn-primary"
					|
					=link_to "Sign up", new_admin_registration_path, :method => :get, :class => "btn btn-primary"
		= yield